GET http://localhost:3003/api/blogs

###
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "CSS Master",
  "author": "Kevin Powell",
  "url": "http://blog.cssmaster.com",
  "likes": 10,
  "userId": "6358235ba6acaf69e2a61fdb"
}

###
GET http://localhost:3003/api/users