GET http://localhost:3003/api/blogs

###
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "JS",
  "author": "Vanilla Man",
  "url": "http://blog.js.com",
  "likes": 53,
  "userId": "6359670f37a2e2f4331e9efd"
}

###
GET http://localhost:3003/api/users